name: PR Check

on:
  push:
    branches: [ base ]
  pull_request:
    branches: [ base ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
  
    - name: Install dependencies
      run: yarn
    - name: Build project
      run: yarn build
    - name: carbon-devtools
      run: lerna run --scope=carbon-devtools test --if-present
    - name: devtools-utilities
      run: lerna run --scope=@carbon/devtools-utilities test --if-present
    - name: devtools-token-server
      run: lerna run --scope=@carbon/devtools-token-server test --if-present
    - name: devtools-demo-site
      run: lerna run --scope=@carbon/devtools-demo-site test --if-present
